anchor_version = "0.14.0"

[programs.localnet]
marinade_referral = "MR2LqxoSbw831bNy68utpu5n4YqBH3AzDmddkgk9LQv"

[programs.devnet]
marinade_referral = "MR2LqxoSbw831bNy68utpu5n4YqBH3AzDmddkgk9LQv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./scripts/test.sh"
